// The full 126-problem catalog (18 topics × 7), from the vault spec's tables.
// Row: [slug, leetcodeId, title, difficulty, mode, acceptedPatterns, v1]
// v1 = true → must be fully authored (1 guided + 3 practice per topic).
export const catalog = {
  'arrays-hashing': [
    ['contains-duplicate', 217, 'Contains Duplicate', 'easy', 'guided', ['hash-set'], true],
    ['group-anagrams', 49, 'Group Anagrams', 'medium', 'guided', ['freq-map', 'hash-map'], true],
    ['valid-anagram', 242, 'Valid Anagram', 'easy', 'practice', ['freq-map'], true],
    ['two-sum', 1, 'Two Sum', 'easy', 'practice', ['hash-map'], true],
    ['top-k-frequent-elements', 347, 'Top K Frequent Elements', 'medium', 'practice', ['freq-map', 'heap'], true],
    ['product-of-array-except-self', 238, 'Product of Array Except Self', 'medium', 'practice', ['prefix'], true],
    ['longest-consecutive-sequence', 128, 'Longest Consecutive Sequence', 'medium', 'practice', ['hash-set'], true],
  ],
  'two-pointers': [
    ['valid-palindrome', 125, 'Valid Palindrome', 'easy', 'guided', ['two-pointers'], true],
    ['three-sum', 15, '3Sum', 'medium', 'guided', ['two-pointers'], true],
    ['two-sum-ii', 167, 'Two Sum II (sorted)', 'medium', 'practice', ['two-pointers'], true],
    ['remove-duplicates-from-sorted-array', 26, 'Remove Duplicates from Sorted Array', 'easy', 'practice', ['two-pointers'], true],
    ['container-with-most-water', 11, 'Container With Most Water', 'medium', 'practice', ['two-pointers'], true],
    ['move-zeroes', 283, 'Move Zeroes', 'easy', 'practice', ['two-pointers'], true],
    ['trapping-rain-water', 42, 'Trapping Rain Water', 'hard', 'practice', ['two-pointers', 'prefix'], false],
  ],
  'sliding-window': [
    ['best-time-to-buy-and-sell-stock', 121, 'Best Time to Buy and Sell Stock', 'easy', 'guided', ['one-pass', 'sliding-window'], true],
    ['longest-substring-without-repeating-characters', 3, 'Longest Substring Without Repeating Characters', 'medium', 'guided', ['sliding-window'], true],
    ['longest-repeating-character-replacement', 424, 'Longest Repeating Character Replacement', 'medium', 'practice', ['sliding-window'], true],
    ['permutation-in-string', 567, 'Permutation in String', 'medium', 'practice', ['sliding-window', 'freq-map'], true],
    ['minimum-size-subarray-sum', 209, 'Minimum Size Subarray Sum', 'medium', 'practice', ['sliding-window'], true],
    ['minimum-window-substring', 76, 'Minimum Window Substring', 'hard', 'practice', ['sliding-window'], false],
    ['sliding-window-maximum', 239, 'Sliding Window Maximum', 'hard', 'practice', ['monotonic-stack', 'sliding-window'], false],
  ],
  stack: [
    ['valid-parentheses', 20, 'Valid Parentheses', 'easy', 'guided', ['stack'], true],
    ['daily-temperatures', 739, 'Daily Temperatures', 'medium', 'guided', ['monotonic-stack'], true],
    ['min-stack', 155, 'Min Stack', 'medium', 'practice', ['stack'], true],
    ['evaluate-reverse-polish-notation', 150, 'Evaluate Reverse Polish Notation', 'medium', 'practice', ['stack'], true],
    ['generate-parentheses', 22, 'Generate Parentheses', 'medium', 'practice', ['backtracking', 'stack'], true],
    ['car-fleet', 853, 'Car Fleet', 'medium', 'practice', ['monotonic-stack', 'sort-sweep'], true],
    ['largest-rectangle-in-histogram', 84, 'Largest Rectangle in Histogram', 'hard', 'practice', ['monotonic-stack'], false],
  ],
  'binary-search': [
    ['binary-search', 704, 'Binary Search', 'easy', 'guided', ['binary-search'], true],
    ['koko-eating-bananas', 875, 'Koko Eating Bananas', 'medium', 'guided', ['binary-search'], true],
    ['search-insert-position', 35, 'Search Insert Position', 'easy', 'practice', ['binary-search'], true],
    ['search-a-2d-matrix', 74, 'Search a 2D Matrix', 'medium', 'practice', ['binary-search'], true],
    ['find-minimum-in-rotated-sorted-array', 153, 'Find Minimum in Rotated Sorted Array', 'medium', 'practice', ['binary-search'], true],
    ['search-in-rotated-sorted-array', 33, 'Search in Rotated Sorted Array', 'medium', 'practice', ['binary-search'], true],
    ['time-based-key-value-store', 981, 'Time Based Key-Value Store', 'medium', 'practice', ['binary-search', 'hash-map'], true],
  ],
  'linked-list': [
    ['reverse-linked-list', 206, 'Reverse Linked List', 'easy', 'guided', ['two-pointers'], true],
    ['linked-list-cycle', 141, 'Linked List Cycle', 'easy', 'guided', ['two-pointers'], true],
    ['merge-two-sorted-lists', 21, 'Merge Two Sorted Lists', 'easy', 'practice', ['two-pointers'], true],
    ['reorder-list', 143, 'Reorder List', 'medium', 'practice', ['two-pointers'], true],
    ['remove-nth-node-from-end', 19, 'Remove Nth Node From End', 'medium', 'practice', ['two-pointers'], true],
    ['add-two-numbers', 2, 'Add Two Numbers', 'medium', 'practice', ['one-pass'], true],
    ['find-the-duplicate-number', 287, 'Find the Duplicate Number', 'medium', 'practice', ['two-pointers'], true],
  ],
  trees: [
    ['invert-binary-tree', 226, 'Invert Binary Tree', 'easy', 'guided', ['dfs'], true],
    ['binary-tree-level-order-traversal', 102, 'Binary Tree Level Order Traversal', 'medium', 'guided', ['bfs'], true],
    ['maximum-depth-of-binary-tree', 104, 'Maximum Depth of Binary Tree', 'easy', 'practice', ['dfs'], true],
    ['balanced-binary-tree', 110, 'Balanced Binary Tree', 'easy', 'practice', ['dfs'], true],
    ['lowest-common-ancestor-of-a-bst', 235, 'Lowest Common Ancestor of a BST', 'medium', 'practice', ['dfs'], true],
    ['validate-binary-search-tree', 98, 'Validate Binary Search Tree', 'medium', 'practice', ['dfs'], true],
    ['kth-smallest-element-in-a-bst', 230, 'Kth Smallest Element in a BST', 'medium', 'practice', ['dfs'], true],
  ],
  tries: [
    ['implement-trie', 208, 'Implement Trie (Prefix Tree)', 'medium', 'guided', ['trie'], true],
    ['design-add-and-search-words', 211, 'Design Add and Search Words', 'medium', 'guided', ['trie', 'dfs'], true],
    ['longest-common-prefix', 14, 'Longest Common Prefix', 'easy', 'practice', ['trie'], true],
    ['replace-words', 648, 'Replace Words', 'medium', 'practice', ['trie'], true],
    ['map-sum-pairs', 677, 'Map Sum Pairs', 'medium', 'practice', ['trie', 'hash-map'], true],
    ['search-suggestions-system', 1268, 'Search Suggestions System', 'medium', 'practice', ['trie', 'two-pointers'], true],
    ['word-search-ii', 212, 'Word Search II', 'hard', 'practice', ['trie', 'backtracking'], false],
  ],
  heap: [
    ['kth-largest-element-in-an-array', 215, 'Kth Largest Element in an Array', 'medium', 'guided', ['heap'], true],
    ['find-median-from-data-stream', 295, 'Find Median from Data Stream', 'hard', 'guided', ['heap'], true],
    ['kth-largest-element-in-a-stream', 703, 'Kth Largest Element in a Stream', 'easy', 'practice', ['heap'], true],
    ['last-stone-weight', 1046, 'Last Stone Weight', 'easy', 'practice', ['heap'], true],
    ['k-closest-points-to-origin', 973, 'K Closest Points to Origin', 'medium', 'practice', ['heap'], true],
    ['task-scheduler', 621, 'Task Scheduler', 'medium', 'practice', ['heap', 'greedy'], true],
    ['merge-k-sorted-lists', 23, 'Merge k Sorted Lists', 'hard', 'practice', ['heap'], false],
  ],
  backtracking: [
    ['subsets', 78, 'Subsets', 'medium', 'guided', ['backtracking'], true],
    ['combination-sum', 39, 'Combination Sum', 'medium', 'guided', ['backtracking'], true],
    ['permutations', 46, 'Permutations', 'medium', 'practice', ['backtracking'], true],
    ['subsets-ii', 90, 'Subsets II', 'medium', 'practice', ['backtracking'], true],
    ['letter-combinations-of-a-phone-number', 17, 'Letter Combinations of a Phone Number', 'medium', 'practice', ['backtracking'], true],
    ['word-search', 79, 'Word Search', 'medium', 'practice', ['backtracking', 'dfs'], true],
    ['palindrome-partitioning', 131, 'Palindrome Partitioning', 'medium', 'practice', ['backtracking', 'dp'], true],
  ],
  graphs: [
    ['number-of-islands', 200, 'Number of Islands', 'medium', 'guided', ['dfs', 'bfs'], true],
    ['course-schedule', 207, 'Course Schedule', 'medium', 'guided', ['dfs', 'bfs'], true],
    ['clone-graph', 133, 'Clone Graph', 'medium', 'practice', ['dfs', 'hash-map'], true],
    ['max-area-of-island', 695, 'Max Area of Island', 'medium', 'practice', ['dfs'], true],
    ['rotting-oranges', 994, 'Rotting Oranges', 'medium', 'practice', ['bfs'], true],
    ['surrounded-regions', 130, 'Surrounded Regions', 'medium', 'practice', ['dfs'], true],
    ['number-of-connected-components', 323, 'Number of Connected Components', 'medium', 'practice', ['dfs', 'union-find'], true],
  ],
  'advanced-graphs': [
    ['network-delay-time', 743, 'Network Delay Time', 'medium', 'guided', ['heap', 'bfs'], true],
    ['min-cost-to-connect-all-points', 1584, 'Min Cost to Connect All Points', 'medium', 'guided', ['heap', 'greedy'], true],
    ['cheapest-flights-within-k-stops', 787, 'Cheapest Flights Within K Stops', 'medium', 'practice', ['bfs', 'heap', 'dp'], true],
    ['reconstruct-itinerary', 332, 'Reconstruct Itinerary', 'hard', 'practice', ['dfs'], false],
    ['swim-in-rising-water', 778, 'Swim in Rising Water', 'hard', 'practice', ['heap', 'binary-search'], false],
    ['alien-dictionary', 269, 'Alien Dictionary', 'hard', 'practice', ['bfs'], true],
    ['word-ladder', 127, 'Word Ladder', 'hard', 'practice', ['bfs'], true],
  ],
  'dp-1d': [
    ['climbing-stairs', 70, 'Climbing Stairs', 'easy', 'guided', ['dp'], true],
    ['coin-change', 322, 'Coin Change', 'medium', 'guided', ['dp'], true],
    ['house-robber', 198, 'House Robber', 'medium', 'practice', ['dp'], true],
    ['decode-ways', 91, 'Decode Ways', 'medium', 'practice', ['dp'], true],
    ['word-break', 139, 'Word Break', 'medium', 'practice', ['dp'], true],
    ['maximum-subarray', 53, "Maximum Subarray (Kadane's)", 'medium', 'practice', ['dp', 'one-pass'], true],
    ['longest-increasing-subsequence', 300, 'Longest Increasing Subsequence', 'medium', 'practice', ['dp', 'binary-search'], true],
  ],
  'dp-2d': [
    ['unique-paths', 62, 'Unique Paths', 'medium', 'guided', ['dp'], true],
    ['longest-common-subsequence', 1143, 'Longest Common Subsequence', 'medium', 'guided', ['dp'], true],
    ['target-sum', 494, 'Target Sum', 'medium', 'practice', ['dp', 'backtracking'], true],
    ['coin-change-ii', 518, 'Coin Change II', 'medium', 'practice', ['dp'], true],
    ['interleaving-string', 97, 'Interleaving String', 'medium', 'practice', ['dp'], true],
    ['edit-distance', 72, 'Edit Distance', 'medium', 'practice', ['dp'], true],
    ['longest-increasing-path-in-a-matrix', 329, 'Longest Increasing Path in a Matrix', 'hard', 'practice', ['dfs', 'dp'], false],
  ],
  greedy: [
    ['jump-game', 55, 'Jump Game', 'medium', 'guided', ['greedy', 'one-pass'], true],
    ['gas-station', 134, 'Gas Station', 'medium', 'guided', ['greedy', 'one-pass'], true],
    ['jump-game-ii', 45, 'Jump Game II', 'medium', 'practice', ['greedy'], true],
    ['hand-of-straights', 846, 'Hand of Straights', 'medium', 'practice', ['greedy', 'freq-map'], true],
    ['partition-labels', 763, 'Partition Labels', 'medium', 'practice', ['greedy', 'sort-sweep'], true],
    ['valid-parenthesis-string', 678, 'Valid Parenthesis String', 'medium', 'practice', ['greedy', 'stack'], true],
    ['merge-triplets-to-form-target', 1899, 'Merge Triplets to Form Target', 'medium', 'practice', ['greedy'], true],
  ],
  intervals: [
    ['merge-intervals', 56, 'Merge Intervals', 'medium', 'guided', ['sort-sweep'], true],
    ['meeting-rooms-ii', 253, 'Meeting Rooms II', 'medium', 'guided', ['sort-sweep', 'heap'], true],
    ['meeting-rooms', 252, 'Meeting Rooms', 'easy', 'practice', ['sort-sweep'], true],
    ['insert-interval', 57, 'Insert Interval', 'medium', 'practice', ['sort-sweep'], true],
    ['non-overlapping-intervals', 435, 'Non-overlapping Intervals', 'medium', 'practice', ['sort-sweep', 'greedy'], true],
    ['interval-list-intersections', 986, 'Interval List Intersections', 'medium', 'practice', ['two-pointers'], true],
    ['minimum-interval-to-include-each-query', 1851, 'Minimum Interval to Include Each Query', 'hard', 'practice', ['heap', 'sort-sweep'], false],
  ],
  'math-geometry': [
    ['rotate-image', 48, 'Rotate Image', 'medium', 'guided', ['math'], true],
    ['spiral-matrix', 54, 'Spiral Matrix', 'medium', 'guided', ['math'], true],
    ['set-matrix-zeroes', 73, 'Set Matrix Zeroes', 'medium', 'practice', ['math'], true],
    ['happy-number', 202, 'Happy Number', 'easy', 'practice', ['hash-set', 'two-pointers'], true],
    ['plus-one', 66, 'Plus One', 'easy', 'practice', ['math'], true],
    ['pow-x-n', 50, 'Pow(x, n)', 'medium', 'practice', ['math'], true],
    ['multiply-strings', 43, 'Multiply Strings', 'medium', 'practice', ['math'], true],
  ],
  'bit-manipulation': [
    ['single-number', 136, 'Single Number', 'easy', 'guided', ['bit-manipulation'], true],
    ['counting-bits', 338, 'Counting Bits', 'easy', 'guided', ['bit-manipulation', 'dp'], true],
    ['number-of-1-bits', 191, 'Number of 1 Bits', 'easy', 'practice', ['bit-manipulation'], true],
    ['reverse-bits', 190, 'Reverse Bits', 'easy', 'practice', ['bit-manipulation'], true],
    ['missing-number', 268, 'Missing Number', 'easy', 'practice', ['bit-manipulation', 'math'], true],
    ['sum-of-two-integers', 371, 'Sum of Two Integers', 'medium', 'practice', ['bit-manipulation'], true],
    ['reverse-integer', 7, 'Reverse Integer', 'medium', 'practice', ['math'], true],
  ],
}
